// The site press: renders the DOM site (home, per-game detail pages,
// sitemap) from the game manifests, as plain HTML strings.
//
// The output is COMMITTED. Nothing at serve time depends on this file — the
// site is static files on a static host, exactly as the charter demands. This
// script exists so that manifests stay the single source of truth for page
// content: edit a manifest (or the templates here), run
//
//   node tools/generate-pages.js
//
// and commit the result. test/site-pages.test.js re-renders every page and
// compares it byte-for-byte against the committed files, so a manifest edit
// that forgets to regenerate fails the suite instead of shipping drift.
//
// Manifest text is untrusted-shaped by design (community submissions will
// supply it later), so every manifest value passes through escapeHtml before
// it reaches markup, and `source` is rendered as text, never as an anchor
// (tickets.md C-003).

import { launchBlockReason, requiredOrientation } from '../shell/cartridge.js';

// Absolute base for canonical links, Open Graph URLs, JSON-LD, and the
// sitemap — the only places the spec requires absolute URLs. Navigation and
// assets stay relative so the site works from any static server and from the
// GitHub Pages subpath alike.
export const SITE_BASE = 'https://jeff-kazzee.github.io/late-shift-arcade/';
export const SITE_NAME = 'Late Shift Arcade';

const FAVICON =
  "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Ctext y='.9em' font-size='90'%3E%F0%9F%95%B9%EF%B8%8F%3C/text%3E%3C/svg%3E";

const GENERATED_NOTE =
  '<!-- Generated by tools/generate-pages.js from games/*/manifest.js.\n' +
  '     Edit the manifests or the generator, then: node tools/generate-pages.js -->';

export function escapeHtml(value) {
  return String(value).replace(/[&<>"']/g, (c) => (
    { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]
  ));
}

// JSON-LD lives inside a <script> element, where "</script>" in data would
// end the element. Escaping "<" closes that door without changing the JSON.
function jsonLd(data) {
  return JSON.stringify(data, null, 2).replace(/</g, '\\u003c');
}

const uniqueSorted = (values) => [...new Set(values)].sort((a, b) => a.localeCompare(b));

function metaBlock({ title, description, canonicalUrl, ogType }) {
  return `  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="theme-color" content="#0b0c14">
  <title>${escapeHtml(title)}</title>
  <meta name="description" content="${escapeHtml(description)}">
  <link rel="canonical" href="${escapeHtml(canonicalUrl)}">
  <meta property="og:type" content="${escapeHtml(ogType)}">
  <meta property="og:site_name" content="${escapeHtml(SITE_NAME)}">
  <meta property="og:title" content="${escapeHtml(title)}">
  <meta property="og:description" content="${escapeHtml(description)}">
  <meta property="og:url" content="${escapeHtml(canonicalUrl)}">
  <meta name="twitter:card" content="summary">
  <meta name="twitter:title" content="${escapeHtml(title)}">
  <meta name="twitter:description" content="${escapeHtml(description)}">
  <link rel="icon" href="${FAVICON}">`;
}

// `prefix` walks from the page back to the repo root: '' for the home page,
// '../../' for games/<slug>/.
function headerBlock(prefix) {
  return `  <header class="site-header">
    <a class="brand" href="${prefix === '' ? './' : prefix}">LATE SHIFT<span>ARCADE</span></a>
    <nav aria-label="Site">
      <a href="${prefix}${prefix === '' ? '#games' : 'index.html#games'}">Games</a>
      <a href="${prefix}${prefix === '' ? '#about' : 'index.html#about'}">About</a>
    </nav>
  </header>`;
}

function footerBlock() {
  const year = 2026;
  return `  <footer class="site-footer">
    <p>${escapeHtml(SITE_NAME)} — small games for the small hours. Every cartridge is AI-made and human-edited.</p>
    <p>No ads, no sign-up, no tracking. High scores stay in your browser.</p>
    <p>© ${year} The Little AI Company · <a href="https://github.com/Jeff-Kazzee/late-shift-arcade" rel="noopener">source on GitHub</a></p>
  </footer>`;
}

function chipGroup(label, group, values) {
  const chips = values
    .map(
      (value) =>
        `        <button type="button" class="chip" data-filter-value="${escapeHtml(value)}" aria-pressed="false">${escapeHtml(value)}</button>`,
    )
    .join('\n');
  return `      <fieldset class="chips" data-filter-group="${group}">
        <legend>${escapeHtml(label)}</legend>
${chips}
      </fieldset>`;
}

function gameCard(manifest) {
  const accent = manifest.artwork.accent;
  const href = `games/${manifest.slug}/`;
  return `        <li>
          <article class="card accent-${escapeHtml(accent)}"
            data-slug="${escapeHtml(manifest.slug)}"
            data-version="${escapeHtml(manifest.version)}"
            data-title="${escapeHtml(manifest.title)}"
            data-genre="${escapeHtml(manifest.genre)}"
            data-modes="${escapeHtml(manifest.modes.join(' '))}"
            data-tags="${escapeHtml(manifest.tags.join(' '))}">
            <p class="card-kicker"><span>${escapeHtml(manifest.genre)}</span><span>${escapeHtml(manifest.players)}P</span></p>
            <h3 class="card-title"><a href="${escapeHtml(href)}">${escapeHtml(manifest.title)}</a></h3>
            <p class="card-summary">${escapeHtml(manifest.summary)}</p>
            <p class="card-foot">
              <span class="card-tags">${escapeHtml(manifest.tags.join(' · '))}</span>
              <span class="card-hi" data-score-slug="${escapeHtml(manifest.slug)}" hidden></span>
            </p>
          </article>
        </li>`;
}

export function renderHomePage(manifests) {
  const title = `${SITE_NAME} — free browser arcade games, open all night`;
  const description =
    `A curated rack of ${manifests.length} small, complete, AI-made arcade games. ` +
    'Free in your browser — no ads, no sign-up, no downloads. Open all night.';

  const genres = uniqueSorted(manifests.map((m) => m.genre));
  const modes = uniqueSorted(manifests.flatMap((m) => m.modes));
  const tags = uniqueSorted(manifests.flatMap((m) => m.tags));

  const structuredData = jsonLd({
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'WebSite',
        name: SITE_NAME,
        url: SITE_BASE,
        description,
      },
      {
        '@type': 'ItemList',
        name: `${SITE_NAME} — the rack`,
        numberOfItems: manifests.length,
        itemListElement: manifests.map((m, i) => ({
          '@type': 'ListItem',
          position: i + 1,
          name: m.title,
          url: `${SITE_BASE}games/${m.slug}/`,
        })),
      },
    ],
  });

  return `<!DOCTYPE html>
<html lang="en">
${GENERATED_NOTE}
<head>
${metaBlock({ title, description, canonicalUrl: SITE_BASE, ogType: 'website' })}
  <link rel="stylesheet" href="shell/site.css">
  <script type="application/ld+json">
${structuredData}
  </script>
</head>
<body>
  <a class="skip-link" href="#games">Skip to the games</a>
${headerBlock('')}
  <main>
    <section class="hero">
      <h1><span class="hero-amber">Open</span> <span class="hero-peri">all night.</span></h1>
      <p class="hero-lede">${escapeHtml(SITE_NAME)} is a curated rack of small, complete, AI-made
        arcade games. No ads, no sign-up, no downloads — pick a cartridge and
        play free in your browser.</p>
      <p class="hero-meta">${manifests.length} games on the rack · high scores stay on your device</p>
      <p class="hero-cta"><a class="button" href="#games">Browse the rack</a></p>
    </section>

    <section id="games" class="rack-section" aria-labelledby="rack-title">
      <h2 id="rack-title">The rack</h2>
      <form class="filters" data-filters hidden aria-label="Search and filter the rack">
        <p class="filters-search">
          <label for="rack-search">Search titles</label>
          <input id="rack-search" type="search" name="q" placeholder="e.g. SNAKE" autocomplete="off" data-filter-search>
        </p>
${chipGroup('Genre', 'genre', genres)}
${chipGroup('Mode', 'modes', modes)}
${chipGroup('Tags', 'tags', tags)}
        <p class="filters-status">
          <span data-rack-count aria-live="polite"></span>
          <button type="button" class="chip chip-clear" data-filter-clear hidden>Clear filters</button>
        </p>
      </form>
      <ol class="rack">
${manifests.map(gameCard).join('\n')}
      </ol>
      <p class="rack-empty" data-rack-empty hidden>
        Nothing on the rack matches.
        <button type="button" class="chip chip-clear" data-filter-clear>Clear filters</button>
      </p>
    </section>

    <section id="about" class="about" aria-labelledby="about-title">
      <h2 id="about-title">About the arcade</h2>
      <p>${escapeHtml(SITE_NAME)} is a small, curated compendium of browser games —
        each one complete, quick to pick up, and built to respect a late hour.
        The cabinet aesthetic is real: launch a game and it plays on a CRT-style
        screen, scanlines and all.</p>
      <p><strong>AI-made, and disclosed.</strong> Every cartridge here ships with a
        material, disclosed AI contribution to its design, code, art, audio, or
        testing. Human editing is expected; the disclosure is the point.</p>
      <p>There are no accounts and no tracking. High scores are stored in your
        browser and never leave your device.</p>
    </section>
  </main>
${footerBlock()}
  <script type="module" src="shell/site.js"></script>
</body>
</html>
`;
}

const PLAY_MODE_MAP = {
  solo: 'https://schema.org/SinglePlayer',
  'local-multiplayer': 'https://schema.org/MultiPlayer',
  'co-op': 'https://schema.org/CoOp',
};

function detailStructuredData(manifest, canonicalUrl, description) {
  const playModes = manifest.modes
    .map((mode) => PLAY_MODE_MAP[mode])
    .filter((mode) => mode !== undefined);
  const data = {
    '@context': 'https://schema.org',
    '@type': 'VideoGame',
    name: manifest.title,
    url: canonicalUrl,
    description,
    genre: manifest.genre,
    gamePlatform: 'Web browser',
    applicationCategory: 'Game',
    operatingSystem: 'Any',
    softwareVersion: manifest.version,
    author: { '@type': 'Organization', name: manifest.creator },
    isAccessibleForFree: true,
    offers: {
      '@type': 'Offer',
      price: '0',
      priceCurrency: 'USD',
      availability: 'https://schema.org/InStock',
    },
  };
  if (playModes.length > 0) data.playMode = playModes;
  return jsonLd(data);
}

function blockedNotice(reason) {
  const message =
    reason === 'suspended'
      ? 'This cartridge is suspended from the rack. The page stays up; the cabinet stays off.'
      : 'This cartridge needs a runtime the in-page cabinet does not host yet, so it cannot be played here.';
  return `          <p class="notice notice-blocked" role="status">${escapeHtml(message)}</p>`;
}

function playRow(manifest) {
  const reason = launchBlockReason(manifest);
  if (reason !== null) return blockedNotice(reason);
  const orientationNote =
    requiredOrientation(manifest) === 'landscape'
      ? 'On phones the cabinet plays in landscape — this page browses fine in portrait, and the game will ask you to rotate.'
      : 'Plays in any orientation, phones included.';
  return `          <p class="play-row">
            <button type="button" class="button button-play" data-play hidden>Insert coin — play now</button>
          </p>
          <noscript><p class="notice">Playing needs JavaScript. Everything written on this page works without it.</p></noscript>
          <p class="orientation-note">${escapeHtml(orientationNote)}</p>`;
}

export function renderDetailPage(manifest) {
  const canonicalUrl = `${SITE_BASE}games/${manifest.slug}/`;
  const title = `${manifest.title} — play free in your browser | ${SITE_NAME}`;
  const description = `${manifest.summary} ${manifest.goal} Play ${manifest.title} free in your browser at ${SITE_NAME}.`;
  const prefix = '../../';
  const orientation = requiredOrientation(manifest);

  return `<!DOCTYPE html>
<html lang="en">
${GENERATED_NOTE}
<head>
${metaBlock({ title, description, canonicalUrl, ogType: 'website' })}
  <link rel="stylesheet" href="${prefix}shell/site.css">
  <script type="application/ld+json">
${detailStructuredData(manifest, canonicalUrl, description)}
  </script>
</head>
<body>
  <a class="skip-link" href="#game">Skip to the game</a>
${headerBlock(prefix)}
  <main id="game" class="detail accent-${escapeHtml(manifest.artwork.accent)}"
    data-slug="${escapeHtml(manifest.slug)}"
    data-version="${escapeHtml(manifest.version)}"
    data-orientation="${escapeHtml(orientation)}"
    data-title="${escapeHtml(manifest.title)}">
    <nav class="crumbs" aria-label="Breadcrumb">
      <a href="${prefix}">All games</a> <span aria-hidden="true">/</span> ${escapeHtml(manifest.title)}
    </nav>
    <article>
      <header class="detail-head">
        <p class="kicker">${escapeHtml(manifest.genre)} · ${escapeHtml(manifest.players)} player${manifest.players === '1' ? '' : 's'} · v${escapeHtml(manifest.version)}</p>
        <h1>${escapeHtml(manifest.title)}</h1>
        <p class="lede">${escapeHtml(manifest.summary)}</p>
${playRow(manifest)}
      </header>

      <div class="detail-columns">
        <section aria-labelledby="goal-title">
          <h2 id="goal-title">The goal</h2>
          <p>${escapeHtml(manifest.goal)}</p>
        </section>

        <section aria-labelledby="facts-title">
          <h2 id="facts-title">How it plays</h2>
          <dl class="facts">
            <dt>Genre</dt><dd>${escapeHtml(manifest.genre)}</dd>
            <dt>Players</dt><dd>${escapeHtml(manifest.players)}</dd>
            <dt>Modes</dt><dd>${escapeHtml(manifest.modes.join(', '))}</dd>
            <dt>Controls</dt><dd>${escapeHtml(manifest.controls.join(' + '))}</dd>
            <dt>Scoreboard</dt><dd>${escapeHtml(manifest.scoreLabel)}</dd>
            <dt>Content</dt><dd>${escapeHtml(manifest.contentNotes.join(' '))}</dd>
          </dl>
        </section>

        <section aria-labelledby="scores-title" data-local-scores hidden>
          <h2 id="scores-title">Best on this device</h2>
          <ol class="score-list" data-score-list></ol>
          <p data-score-empty hidden>No scores yet — the first run sets the bar.</p>
        </section>

        <section aria-labelledby="provenance-title">
          <h2 id="provenance-title">Provenance</h2>
          <p>By ${escapeHtml(manifest.creator)}. ${escapeHtml(manifest.madeWith)}</p>${
            manifest.source === undefined
              ? ''
              : `\n          <p class="source-line">Source: <span class="mono">${escapeHtml(manifest.source)}</span></p>`
          }
        </section>
      </div>
    </article>
  </main>
${footerBlock()}
  <script type="module" src="${prefix}shell/player.js"></script>
</body>
</html>
`;
}

export function renderSitemap(manifests) {
  const urls = [SITE_BASE, ...manifests.map((m) => `${SITE_BASE}games/${m.slug}/`)];
  const entries = urls
    .map((url) => `  <url>\n    <loc>${escapeHtml(url)}</loc>\n  </url>`)
    .join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries}
</urlset>
`;
}

export function renderRobots() {
  return `User-agent: *
Allow: /

Sitemap: ${SITE_BASE}sitemap.xml
`;
}

// --- CLI: write the committed files ---------------------------------------

const isMain = await (async () => {
  if (typeof process === 'undefined' || !process.argv?.[1]) return false;
  const { pathToFileURL } = await import('node:url');
  return import.meta.url === pathToFileURL(process.argv[1]).href;
})();

if (isMain) {
  const [{ writeFileSync, mkdirSync }, { fileURLToPath }] = await Promise.all([
    import('node:fs'),
    import('node:url'),
  ]);
  const { cartridges } = await import('../games/registry.js');
  const manifests = cartridges.map((entry) => entry.manifest);
  const root = fileURLToPath(new URL('..', import.meta.url));

  writeFileSync(`${root}index.html`, renderHomePage(manifests));
  writeFileSync(`${root}sitemap.xml`, renderSitemap(manifests));
  writeFileSync(`${root}robots.txt`, renderRobots());
  for (const manifest of manifests) {
    mkdirSync(`${root}games/${manifest.slug}`, { recursive: true });
    writeFileSync(`${root}games/${manifest.slug}/index.html`, renderDetailPage(manifest));
  }
  console.log(`wrote index.html, sitemap.xml, robots.txt, and ${manifests.length} detail pages`);
}
